# https://cert-manager.io/docs/trust/trust-manager/
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: demo-ca-bundle
spec:
  sources:
    - secret:
        name: demo-ca
        key: ca.crt
  target:
    configMap:
      key: ca-bundle.crt
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: default
